import CreateForm from './components/cp/core/CreateForm';
import Listing from './components/cp/forms/Listing';
import FormPublishForm from './components/cp/forms/PublishForm';
import FieldsBuilder from './components/cp/fields/Builder';
import NotificationsEditForm from './components/cp/notifications/EditForm';
import NotificationsListing from './components/cp/notifications/Listing';
import SubmissionsListing from './components/cp/submissions/Listing';
import FeedsCreateForm from './components/cp/feeds/CreateForm';
import FeedsEditForm from './components/cp/feeds/EditForm';
import FeedsListing from './components/cp/feeds/Listing';
import FeedCreateButton from './components/cp/feeds/CreateButton';
import SubmissionNotes from './components/cp/submissions/Notes';
import SubmissionNote from './components/cp/submissions/Note';
import AnonymousAssetsFieldtype from './components/cp/fieldtypes/AnonymousAssetsFieldtype';
import AddressLookupFieldtype from './components/cp/fieldtypes/AddressLookupFieldtype';
import CalculatorFieldtype from './components/cp/fieldtypes/CalculatorFieldtype';
import ColorInputFieldtype from './components/cp/fieldtypes/ColorInputFieldtype';
import DateInputFieldtype from './components/cp/fieldtypes/DateInputFieldtype';
import DividerFieldtype from './components/cp/fieldtypes/DividerFieldtype';
import EmailInputFieldtype from './components/cp/fieldtypes/EmailInputFieldtype';
import HiddenInputFieldtype from './components/cp/fieldtypes/HiddenInputFieldtype';
import MonthInputFieldtype from './components/cp/fieldtypes/MonthInputFieldtype';
import NumberInputFieldtype from './components/cp/fieldtypes/NumberInputFieldtype';
import PasswordInputFieldtype from './components/cp/fieldtypes/PasswordInputFieldtype';
import TelInputFieldtype from './components/cp/fieldtypes/TelInputFieldtype';
import TextareaInputFieldtype from './components/cp/fieldtypes/TextareaInputFieldtype';
import TextInputFieldtype from './components/cp/fieldtypes/TextInputFieldtype';
import TimeInputFieldtype from './components/cp/fieldtypes/TimeInputFieldtype';
import UrlInputFieldtype from './components/cp/fieldtypes/UrlInputFieldtype';
import WeekInputFieldtype from './components/cp/fieldtypes/WeekInputFieldtype';

Statamic.booting(() => {
    // CP views
    Statamic.component('advanced-forms-core-create', CreateForm);
    Statamic.component('advanced-forms-listing', Listing);
    Statamic.component('advanced-forms-edit-form', FormPublishForm);
    Statamic.component('advanced-forms-fields-builder', FieldsBuilder);
    Statamic.component('advanced-forms-notification-edit-form', NotificationsEditForm);
    Statamic.component('advanced-forms-notifications-listing', NotificationsListing);
    Statamic.component('advanced-forms-submissions-listing', SubmissionsListing);
    Statamic.component('advanced-forms-feed-create-form', FeedsCreateForm);
    Statamic.component('advanced-forms-feed-edit-form', FeedsEditForm);
    Statamic.component('advanced-forms-feeds-listing', FeedsListing);
    Statamic.component('advanced-forms-create-button', FeedCreateButton);
    Statamic.component('advanced-forms-submission-notes', SubmissionNotes);
    Statamic.component('advanced-forms-submission-note', SubmissionNote);

    // Fieldtypes
    Statamic.$components.register('anonymous-assets-fieldtype', AnonymousAssetsFieldtype);
    Statamic.$components.register('address_lookup-fieldtype', AddressLookupFieldtype);
    Statamic.$components.register('calculator-fieldtype', CalculatorFieldtype);
    Statamic.$components.register('color_input-fieldtype', ColorInputFieldtype);
    Statamic.$components.register('date_input-fieldtype', DateInputFieldtype);
    Statamic.$components.register('divider-fieldtype', DividerFieldtype);
    Statamic.$components.register('email_input-fieldtype', EmailInputFieldtype);
    Statamic.$components.register('hidden_input-fieldtype', HiddenInputFieldtype);
    Statamic.$components.register('month_input-fieldtype', MonthInputFieldtype);
    Statamic.$components.register('number_input-fieldtype', NumberInputFieldtype);
    Statamic.$components.register('password_input-fieldtype', PasswordInputFieldtype);
    Statamic.$components.register('tel_input-fieldtype', TelInputFieldtype);
    Statamic.$components.register('textarea_input-fieldtype', TextareaInputFieldtype);
    Statamic.$components.register('text_input-fieldtype', TextInputFieldtype);
    Statamic.$components.register('time_input-fieldtype', TimeInputFieldtype);
    Statamic.$components.register('url_input-fieldtype', UrlInputFieldtype);
    Statamic.$components.register('week_input-fieldtype', WeekInputFieldtype);
});
